# DB_SERVER: database
# DB_PORT: 3306
# DB_DATABASE: symfony
# DB_USER: symfony
# DB_PASSWORD: symfony
# @todo-craft update
name: craftstarter
recipe: symfony
config:
  php: '8.0'
  webroot: public
  xdebug: true
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver:
    # @todo-craft update
    - craftstarter.lndo.site
