# @todo-craft update
# URLs: https://craftstarter.lndo.site/ or __________
# DB_SERVER: database
# DB_PORT: 3306
# DB_DATABASE: craft
# DB_USER: craft
# DB_PASSWORD: craft
# @todo-craft update
name: craftstarter
recipe: symfony
config:
  config:
    php: lando_php.ini
  php: '8.1'
  webroot: public
  xdebug: true
services:
  database:
    creds:
      user:     craft
      password: craft
      database: craft
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver:
    # @todo-craft update
    - craftstarter.lndo.site
