field: ec34d844-46a7-4389-965e-a1a4048a0798 # Accordion
fieldLayouts:
  5c9f770e-3ac8-40bf-93b6-b98cd735c56f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d438c1a3-baf2-4366-9942-1dfcd9b7454a # Accordion Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bfe0f7a-a616-4909-b4c9-a472d0653c95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbf76707-952f-4a1e-940a-41822a3a51bf # Accordion Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 501c78ac-b0e3-4692-b932-8f21c3149edc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d9f0b31-c87e-4291-8103-fcfb462b5e21 # Accordion Content
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4c2206a-5758-40d5-9bcd-9b90bf1d465d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f345764-41de-4e41-b59d-3a31de0ae1ad
        userCondition: null
fields:
  1d9f0b31-c87e-4291-8103-fcfb462b5e21: # Accordion Content
    columnSuffix: ovdugtuh
    contentColumnType: text
    fieldGroup: null
    handle: accordionContent
    instructions: null
    name: 'Accordion Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d438c1a3-baf2-4366-9942-1dfcd9b7454a: # Accordion Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accordionIcon
    instructions: null
    name: 'Accordion Icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:95ce255a-2242-4832-a7bd-6ef99ba868c1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c2939a10-1c98-4789-8a72-cc8985158379' # Blog
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fbf76707-952f-4a1e-940a-41822a3a51bf: # Accordion Heading
    columnSuffix: iqtptnht
    contentColumnType: text
    fieldGroup: null
    handle: accordionHeading
    instructions: null
    name: 'Accordion Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: accordion
name: Accordion
sortOrder: 1
