field: 8657041f-bf73-4ed2-a11e-fce4a4195788 # Herobar
fieldLayouts:
  0ea174a2-617c-4d21-b4e7-3773d97a87b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 68c02e53-bd4b-45e6-8721-dfa278498dbb # Herobar Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 137144ce-7c7c-4cef-95e8-c737b79a007d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2062b2bd-5662-4e7c-a7cf-0f05a4b4da60 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb7b634f-5780-4144-89f9-8228402711da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08c0e2a2-aaf5-48e9-bed6-e1f8fc7ce863 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39e84ed4-dda3-4286-9858-da5a0bdf8766
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b2e948bb-ce8f-4b37-b9e8-8c59de235b8d
        userCondition: null
fields:
  08c0e2a2-aaf5-48e9-bed6-e1f8fc7ce863: # Subheading
    columnSuffix: mybfonzf
    contentColumnType: text
    fieldGroup: null
    handle: subheading
    instructions: null
    name: Subheading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  68c02e53-bd4b-45e6-8721-dfa278498dbb: # Herobar Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: herobarImage
    instructions: 'Image should be 1290x538px or larger and the same proportions'
    name: 'Herobar Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:95ce255a-2242-4832-a7bd-6ef99ba868c1' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c2939a10-1c98-4789-8a72-cc8985158379' # Blog
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2062b2bd-5662-4e7c-a7cf-0f05a4b4da60: # Heading
    columnSuffix: yhwabiuo
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: herobar
name: Herobar
sortOrder: 1
