field: 733fd8a3-3ba2-49a2-bb77-c60b52b6bc66 # Post Content
fieldLayouts:
  bc20d52e-2493-47df-89e3-b63139731a31:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 64ec34a3-ecdf-4518-b59f-faaa5d33b8a9 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6397da29-9c20-4124-b59a-381c81cfe0cb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2c830cd9-4e6c-4f49-9445-9e224a1638ab
        userCondition: null
fields:
  64ec34a3-ecdf-4518-b59f-faaa5d33b8a9: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:c2939a10-1c98-4789-8a72-cc8985158379' # Blog
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c2939a10-1c98-4789-8a72-cc8985158379' # Blog
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
