fieldLayouts:
  a286551f-1887-47ca-b854-5d31925a390f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e318be56-d266-42c6-ad19-02532e74e28a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f5b97fd-8f12-4f4e-9ab4-f9db01767842
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a53bb2c9-fbc4-47b0-a411-0f19c9f82f5b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9250cf7-3f95-4113-85e5-0140eb887bfe # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fc85c5e-1b52-4131-a560-41af5e3fefb4
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e33ced61-816b-4c98-9599-07d995670307
        userCondition: null
handle: about
hasTitleField: true
name: About
section: d9b45246-8d18-46e0-9a98-ac7b65120828 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
