color: null
fieldLayouts:
  201979ee-6eab-46c3-8e5e-a10e4a411890:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-02T18:18:23+00:00'
            elementCondition: null
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd37315a-6c19-40fa-83c2-0ec0368a9788
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2197f60e-6d94-41cf-898c-f106e21f643e
        userCondition: null
handle: accordionContent
hasTitleField: false
icon: ''
name: 'Accordion Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
