color: null
fieldLayouts:
  43191508-5d09-4f9f-a047-0f9150b12e1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-02T18:17:32+00:00'
            elementCondition: null
            fieldUid: 55c62e14-e98e-4d1a-a181-845f6ebf20e4 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20a35178-1ce6-4458-bd9a-4e05a152d0ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1021c69e-6d0e-48be-a6f7-729957c75b62
        userCondition: null
handle: accordionHeading
hasTitleField: false
icon: ''
name: 'Accordion Heading'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
