color: null
fieldLayouts:
  b6e2d235-c2a9-444c-a111-c612313f8857:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T20:09:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 55c62e14-e98e-4d1a-a181-845f6ebf20e4 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 681d9494-c7a6-4e70-9e50-941b61105de7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: addde9dd-00f9-4dd5-8d0c-a5652cab98c9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T20:09:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 80ffc64e-4e53-4ba1-8e8f-95d4f45b8946 # Text Align
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c88cd565-d5a5-443a-a47f-c163323d5cc9
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 78d701c5-c6d4-4309-adca-f1a5918d3b6a
        userCondition: null
handle: cardHeading
hasTitleField: false
icon: null
name: 'Card Heading'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
