allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  3099ce89-0a77-4b57-9a8b-dff3d83086e0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-27T18:33:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8a7f167c-88c5-43d8-873a-50caa35f5962 # Column Proportions
            handle: null
            instructions: null
            label: 'Column Proportions'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1a2845e-823e-4d49-ac9f-ea18d0930782
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-28T18:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1ea0bb2d-a3bc-43be-84f5-211bbb962155 # Columns Full Width
            handle: fullWidth
            instructions: null
            label: 'Full Width'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d6f57b9-30ce-4052-ad48-2f5efce483f6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-27T18:13:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7c94e8f1-c92f-47b8-ac85-3795e822ff9a # Blocks Inside - Left
            handle: null
            instructions: null
            label: 'Left Column'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af9a37c5-ba0f-4523-acd8-61a02e1f05cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-27T18:15:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 13a0788b-0c2f-4f60-9cde-f5a2155f12b3 # Blocks Inside - Right
            handle: null
            instructions: null
            label: 'Right Column'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23ba42a3-4387-4e91-9b70-f9c1c955bc62
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 78733ec6-a27d-4718-9fd5-76f4832e98f6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-27T18:40:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da882736-cf1b-44c9-bccf-1e9e14325b50
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-27T18:40:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element ID
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d62451c-85f0-4cd0-8a7c-51d5a10a5256
            userCondition: null
            warning: null
            width: 50
        name: Attributes
        uid: d9168717-2e41-430a-8447-0de2b43d6581
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-08-27T18:09:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: 'Only appears in admin'
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92884fa2-7706-4062-a30b-bff047b9726d
            userCondition: null
            warning: null
            width: 100
        name: Admin
        uid: 90b945a9-adb6-4b69-8eee-55a203e87a15
        userCondition: null
    thumbFieldKey: null
handle: columnsTwo
hasTitleField: true
icon: table-columns
name: '2 Columns'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{title ?: (blocksInsideLeft.type('heading').one().heading.plainText ?? null) ?: (blocksInsideRight.type('heading').one().heading.plainText ?? null) ?: '2 Columns'}"
