fieldLayouts:
  a70ef132-178a-45e2-9278-8f092c4c3325:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f64940f5-0c91-48df-803d-25c18827c20a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3b89ada-8774-49a8-8e14-9916373409d0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a244c77b-941c-4630-8158-794f2a480bb5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fbc6babb-8a67-4aac-9a2b-ca33e3e7971a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9250cf7-3f95-4113-85e5-0140eb887bfe # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a04d4a85-7091-476c-a5bf-d3c8eaa880d6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: f1ef4fe5-bc19-4d04-8a0a-16b80c76c179
        userCondition: null
handle: contactThanks
hasTitleField: false
name: 'Contact Thanks'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
