color: null
fieldLayouts:
  909e3be5-fce7-4edc-b183-4248040bfea6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-30T23:16:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 511b4125-7210-4377-af9b-8ef59b8aa7ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-26T20:40:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 84ee4464-5ee9-437c-8ce9-ac6cd3d50663 # Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ea8e7af-8cc5-449a-8010-339d43f36eab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e1a653a5-df97-4a39-8709-2da116f23ee0
        userCondition: null
handle: gallery
hasTitleField: true
icon: null
name: Gallery
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
