color: null
fieldLayouts:
  8290f42c-be7d-495f-930d-62189f73dc3d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-02T16:46:19+00:00'
            elementCondition: null
            fieldUid: 5f2efa0b-1e87-4d02-a636-f17256ef85d1 # Block Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8368a790-29ed-4910-8fec-2b1ea60a3fe1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-30T00:13:57+00:00'
            elementCondition: null
            fieldUid: 55c62e14-e98e-4d1a-a181-845f6ebf20e4 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e95a9e0-5571-4685-8d60-5a6ff21e9971
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2803b717-6c7e-4532-9154-462c5c49f70b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-02T16:50:32+00:00'
            elementCondition: null
            fieldUid: 80ffc64e-4e53-4ba1-8e8f-95d4f45b8946 # Text Align
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8c6d865-95cf-4f22-9a2a-aa783bd59720
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: de238c42-1429-4948-9f49-ea8383fa7b24
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T22:12:44+00:00'
            elementCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c113e3ed-b6c6-4b1f-8620-dc72895742e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T22:12:44+00:00'
            elementCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 230252c5-1995-4299-9068-11b99fd35e7e
            userCondition: null
            warning: null
            width: 100
        name: Attributes
        uid: 6e13ed9e-2bc2-44d3-bce2-e08823a1d0be
        userCondition: null
handle: heading
hasTitleField: false
icon: ''
name: Heading
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
