color: null
fieldLayouts:
  bc20d52e-2493-47df-89e3-b63139731a31:
    cardView:
      - 'layoutElement:6397da29-9c20-4124-b59a-381c81cfe0cb'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            elementCondition: null
            fieldUid: 64ec34a3-ecdf-4518-b59f-faaa5d33b8a9
            handle: image
            includeInCards: true
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6397da29-9c20-4124-b59a-381c81cfe0cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T16:21:50+00:00'
            elementCondition: null
            fieldUid: 809bc4b9-bc38-4d55-bb2c-4f2983ea3cfc # Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b761546f-8e73-45fd-8b4e-1dbdce3ccf94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T16:21:50+00:00'
            elementCondition: null
            fieldUid: 55db9051-b419-4237-b226-acfb99d40498 # Image Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e87a6359-ed14-46e9-acca-8f33824de65d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2c830cd9-4e6c-4f49-9445-9e224a1638ab
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-02T16:43:03+00:00'
            elementCondition: null
            fieldUid: 5f2efa0b-1e87-4d02-a636-f17256ef85d1 # Block Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3bf449f-7aa6-4bf0-b23a-a1933672a3d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T16:21:50+00:00'
            elementCondition: null
            fieldUid: 6eedec95-8e5a-49e4-8206-33ff056d1664 # Image Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 808ac820-aa23-4fd8-b2e1-f6658dc79a55
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 69894a45-d5c3-4e21-af38-4cc66ff77b54
        userCondition: null
handle: image
hasTitleField: false
icon: ''
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
