color: null
fieldLayouts:
  bc20d52e-2493-47df-89e3-b63139731a31:
    cardView:
      - 'layoutElement:6397da29-9c20-4124-b59a-381c81cfe0cb'
      - 'layoutElement:e3bf449f-7aa6-4bf0-b23a-a1933672a3d5'
      - 'layoutElement:5ad0c4e0-5dc7-4122-84c4-fc2f504ea355'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            elementCondition: null
            fieldUid: 64ec34a3-ecdf-4518-b59f-faaa5d33b8a9 # Post Content - Image
            handle: image
            includeInCards: true
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6397da29-9c20-4124-b59a-381c81cfe0cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T16:21:50+00:00'
            elementCondition: null
            fieldUid: 809bc4b9-bc38-4d55-bb2c-4f2983ea3cfc # Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b761546f-8e73-45fd-8b4e-1dbdce3ccf94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T16:21:50+00:00'
            elementCondition: null
            fieldUid: 55db9051-b419-4237-b226-acfb99d40498 # Image Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e87a6359-ed14-46e9-acca-8f33824de65d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2c830cd9-4e6c-4f49-9445-9e224a1638ab
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-02T16:43:03+00:00'
            elementCondition: null
            fieldUid: 5f2efa0b-1e87-4d02-a636-f17256ef85d1 # Block Width
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3bf449f-7aa6-4bf0-b23a-a1933672a3d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T16:21:50+00:00'
            elementCondition: null
            fieldUid: 6eedec95-8e5a-49e4-8206-33ff056d1664 # Image Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 808ac820-aa23-4fd8-b2e1-f6658dc79a55
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T23:47:37+00:00'
            elementCondition: null
            fieldUid: 17ed004b-264f-4318-be4a-407867219887 # Image Align
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dde483de-2806-49e4-9549-56f0ebd741d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T23:56:41+00:00'
            elementCondition: null
            fieldUid: c3bdff5b-2014-42e0-87b1-372f17b8ec0e # Image Vertical Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21e42079-fbb9-46b6-b5f9-694ae79e8682
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: 69894a45-d5c3-4e21-af38-4cc66ff77b54
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T22:13:59+00:00'
            elementCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ad0c4e0-5dc7-4122-84c4-fc2f504ea355
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T22:13:59+00:00'
            elementCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec4ebb93-3fd8-40b9-aa85-569b33a2cdb9
            userCondition: null
            warning: null
            width: 100
        name: Attributes
        uid: 59737b3d-4fc9-41a0-b985-93f9d15fe487
        userCondition: null
handle: image
hasTitleField: false
icon: ''
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
