fieldLayouts:
  1b51347e-5106-4a6c-b9ed-1bc77dd0d9fa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1515d6fd-af6a-41d1-b6a5-d9d58ba57788
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa2ad779-73fc-442c-9c92-1ae549690452 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2d59821-c51c-4e47-8331-9d03400858a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c929dd78-a952-444d-a24b-6779666bee69
        userCondition: null
handle: services
hasTitleField: true
name: Services
section: 941223b2-225a-4a1c-8095-3ef96f00d2f5 # Services
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
