fieldLayouts:
  1fa47ce7-a314-4129-b529-62e8670bab10:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 492a43fa-79d3-42a7-a799-d65928222097
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48d1c2a6-ebc9-4293-84ba-6aa96e64198a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b33fbb6-b3b3-49a1-b4a0-60fc46c3a1d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8657041f-bf73-4ed2-a11e-fce4a4195788 # Herobar
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f0b7f24-82bb-45a8-a607-7e22fb7eccf2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 34760064-e51b-4b4d-95fe-27452f5ae69b
        userCondition: null
handle: testPage
hasTitleField: true
name: 'Test Page'
section: 91f4ab67-2475-4a48-8d83-67f32c7d6fd7 # Test Page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
