color: null
fieldLayouts:
  599523b1-d5da-4db4-a3a7-d37a4369be1b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-05T00:37:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecc3052c-636d-4494-b08a-f61fc4ce3715
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T21:14:00+00:00'
            elementCondition: null
            fieldUid: dadbdcf6-f9f1-4d87-9c01-c567a77669ff # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eaa7be8-1a2c-476a-a2d8-595da16d02c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23f30558-a653-4232-9b68-b6858f3132a9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T22:19:27+00:00'
            elementCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de2d54f1-f3fd-4c6c-b89a-9bc805951b97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T22:19:27+00:00'
            elementCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 489e175d-83f3-4a25-8537-6df121bdfd56
            userCondition: null
            warning: null
            width: 100
        name: Attributes
        uid: eb139aec-ccdf-4378-b378-ffcb602718fa
        userCondition: null
handle: video
hasTitleField: true
icon: ''
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
