color: null
fieldLayouts:
  599523b1-d5da-4db4-a3a7-d37a4369be1b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T21:14:00+00:00'
            elementCondition: null
            fieldUid: dadbdcf6-f9f1-4d87-9c01-c567a77669ff # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eaa7be8-1a2c-476a-a2d8-595da16d02c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23f30558-a653-4232-9b68-b6858f3132a9
        userCondition: null
handle: video
hasTitleField: false
icon: ''
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
