childBlocks: null
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  bcb3c4f6-d7b3-4eec-95f2-249b1b31bcf1:
    tabs:
      -
        elements:
          -
            fieldUid: ec34d844-46a7-4389-965e-a1a4048a0798 # Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
group: null
handle: accordion
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Accordion
sortOrder: 3
topLevel: false
