childBlocks: null
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  66744925-cf13-4770-a0be-69586080c2cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7b6416c2-1b79-40c4-afad-8d1678b85a34 # Button
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df3defa1-1bc8-4fd2-8078-aa5c60622f95
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b7eb0b61-0927-4f8f-be25-a868e9ef9a7d
        userCondition: null
group: null
handle: button
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Button
sortOrder: 5
topLevel: false
