childBlocks: null
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  08851733-0ee5-4a56-b2d4-316082f98579:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5145a29-7303-44ba-baf2-b9f1667c3aaf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 725f9323-ca0a-48c4-a54f-c8ae560f5673
        userCondition: null
group: null
handle: card
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Card
sortOrder: 9
topLevel: false
