childBlocks: null
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  08851733-0ee5-4a56-b2d4-316082f98579:
    tabs:
      -
        elements:
          -
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
group: null
handle: card
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Card
sortOrder: 7
topLevel: false
