childBlocks:
  - accordion
  - button
  - cards
  - heading
  - image
  - imageGrid
  - imagePair
  - video
  - textBlock
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  5aff4779-f01c-44cc-a22b-03703924570a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: af5c13ac-669e-4c56-af44-8ce554383c94 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9eb61ec-35d6-4424-9f8c-0497ad90d44d
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: 17815879-e3b8-473e-afe4-824ba09b456d
        userCondition: null
group: null
handle: column
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Column
sortOrder: 3
topLevel: false
