childBlocks: null
description: null
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  b1b3fcfe-3fc2-4993-84b4-dcfc9ab91008:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 55c62e14-e98e-4d1a-a181-845f6ebf20e4 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdb5eadf-ce83-4677-a4d6-217884bae1f4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c6d144ad-4c48-4d46-9cbe-9df0bb7f37d5
        userCondition: null
group: null
handle: heading
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Heading
sortOrder: 6
topLevel: false
