childBlocks: null
description: null
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  b1b3fcfe-3fc2-4993-84b4-dcfc9ab91008:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 55c62e14-e98e-4d1a-a181-845f6ebf20e4 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdb5eadf-ce83-4677-a4d6-217884bae1f4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c6d144ad-4c48-4d46-9cbe-9df0bb7f37d5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 80ffc64e-4e53-4ba1-8e8f-95d4f45b8946 # Text Align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3fe3d83-869c-4593-8c2d-9ed62c75e788
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e16fd2de-54c9-4363-a6bd-d3a6756c0720 # Uppercase
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef440c86-9102-4d26-a415-bcc7fe1cdcb2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b3b92e1-639f-41f7-8186-4cefa62703d0
            userCondition: null
            warning: null
            width: 25
        name: Styles
        uid: 7fe853be-1342-4a2e-b8f0-29f315839282
        userCondition: null
group: null
handle: heading
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Heading
sortOrder: 7
topLevel: false
