childBlocks: null
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  3312b0b9-eb19-4181-bef3-79be2a3b1916:
    tabs:
      -
        elements:
          -
            fieldUid: 8657041f-bf73-4ed2-a11e-fce4a4195788 # Herobar
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
group: null
handle: herobar
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Herobar
sortOrder: 2
topLevel: false
