childBlocks: null
conditions: null
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  99d6e052-583d-4334-acf2-0633fb8b7d1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8918d4f4-0186-49a9-96b8-c77845095068 # Image Pair
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5a6527f-4317-4a45-b462-60d80cf36029
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26587b94-f519-4761-9022-df6a2b20f776
        userCondition: null
group: null
groupChildBlockTypes: true
handle: imagePair
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Image Pair'
topLevel: false
