childBlocks: null
conditions: null
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  17586dd0-e809-4c71-a00f-37602b346889:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 486e0db8-6cbd-4cd7-85af-77040ab2b43c # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e3eb8bc-adf0-4dce-bffc-30d2ace76347
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 809bc4b9-bc38-4d55-bb2c-4f2983ea3cfc # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e609bf1-94c3-4190-8f60-9bdfb34d7c75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55db9051-b419-4237-b226-acfb99d40498 # Image Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b63fe27d-c971-42a4-8abc-3c00a28ef543
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43a35f7a-c4b2-4316-9eea-7ba86dd2e665
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6eedec95-8e5a-49e4-8206-33ff056d1664 # Image Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ca23e8b-8d23-4f44-8098-dbcfdb6dfdc6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 78f2dee3-a665-47f0-a7f2-c479a0032003 # Image Vertical Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4affc14-d2c5-464c-96d1-2efd121c416f
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: a8f81586-fc90-4d03-98c6-70afeea79fdf
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
topLevel: false
