childBlocks: null
description: null
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  bbae270c-3227-4ebd-b9b1-a8bc038689d0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 75818205-6564-4823-af02-9b438b462929 # Image Grid
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1ee5501-48a3-4da6-952b-8dc24539ef47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 016efa72-2336-4dc7-b3bc-6fed2ba615bd
        userCondition: null
group: null
handle: imageGrid
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Image Grid'
sortOrder: 12
topLevel: false
