childBlocks: null
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  0b795782-7b38-4d53-8b79-7e3de4e1365b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3113868a-a12e-4195-8e78-8ba0eb507fdb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ae059dbb-0a3d-4897-a677-e31ca1102ca0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 95e5ecb2-f98f-455b-bd08-580743d5fa53 # Text Align Center (Mobile)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7088eaae-8855-4ec0-b21c-49c50cabcaa8
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: 3d14e3e5-f55f-40b0-adaf-08809af3021d
        userCondition: null
group: null
handle: textBlock
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Text Block'
sortOrder: 13
topLevel: false
