childBlocks: null
conditions: null
description: null
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  060ee5ce-ae04-47bd-9f4f-06230cd254a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dadbdcf6-f9f1-4d87-9c01-c567a77669ff # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b94edc8-63e8-499d-9d45-5ee089d2ba90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5236179c-e4bc-466b-bd36-180d599f2bd2
        userCondition: null
group: null
groupChildBlockTypes: true
handle: video
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Video
sortOrder: 14
topLevel: false
