childBlocks: null
conditions: null
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  bcb3c4f6-d7b3-4eec-95f2-249b1b31bcf1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec34d844-46a7-4389-965e-a1a4048a0798 # Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32143479-7d17-4712-b524-f8fec867346b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a735268-0b83-4c78-be1d-a9bb1b083ca5
        userCondition: null
group: null
groupChildBlockTypes: true
handle: accordion
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Accordion
topLevel: false
