childBlocks:
  - column
conditions: null
description: ''
enabled: true
field: e3b89ada-8774-49a8-8e14-9916373409d0 # Blocks
fieldLayouts:
  5b49e2ef-8486-4688-b060-6ecc41efaff8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element Id
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea619c64-7750-446b-b389-0e8a3306f7e6
            userCondition: null
            warning: null
            width: 50
        name: Styles
        uid: a2698a33-01c7-43f9-8830-6e4cce32e873
        userCondition: null
group: null
groupChildBlockTypes: true
handle: columns
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Columns
topLevel: true
