columnSuffix: ovdugtuh
handle: accordionContent
instructions: null
name: 'Accordion - Accordion - Accordion Content'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 3ccf3102-3b57-4a41-8571-700d76e6afca # Standard
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
