columnSuffix: null
handle: blockWidth
instructions: "Select a column width of block out of 12.\r\ni.e. 12/12 = 100% width. 6/12 = 50%"
name: 'Block Width'
searchable: false
settings:
  defaultValue: 12
  max: 12
  min: 1
  step: 1
  suffix: 'out of 12'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
