columnSuffix: null
handle: blockWidth
instructions: 'Select percentage width of block.'
name: 'Block Width'
searchable: false
settings:
  defaultValue: 12
  max: 12
  min: 1
  step: 1
  suffix: '%'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
