columnSuffix: null
contentColumnType: string
handle: button
instructions: null
name: Button
searchable: false
settings:
  entryTypes:
    - 52c2bd62-048d-4695-be78-f0110b0727de # Button
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
