columnSuffix: null
handle: card
instructions: null
name: Card
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - c0a4b738-d7e7-4400-9576-7e279127345f # Card Heading
    - 681bd2d8-cf04-4239-bcc5-a1bbcc3c8625 # Card Text Block
    - fe9ab73f-86a5-45dd-8efd-91ea40ad88ac # Card Image
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
