columnSuffix: gfgryzxg
contentColumnType: string
fieldGroup: c763c881-9bb8-49e1-8297-dc71ed74d29a # Common
handle: categoryNavSection
instructions: null
name: Section
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Furniture
        -
          - value
          - officeFurnitureSubpages
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Telus
        -
          - value
          - telusSubpages
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Xerox
        -
          - value
          - xeroxSubpages
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
