columnSuffix: gfgryzxg
contentColumnType: string
handle: categoryNavSection
instructions: null
name: Section
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Furniture
        -
          - value
          - officeFurnitureSubpages
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Telus
        -
          - value
          - telusSubpages
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Xerox
        -
          - value
          - xeroxSubpages
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
