columnSuffix: mphjzkyx
contentColumnType: string(600)
fieldGroup: 542b6e5b-f553-4be6-8520-672fcf3db4f0 # Styles
handle: classes
instructions: 'CSS classes too apply to the wrapper element.'
name: Classes
searchable: false
settings:
  byteLimit: null
  charLimit: 150
  code: true
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
