columnSuffix: mphjzkyx
handle: classes
instructions: 'CSS classes to apply to the wrapper element.'
name: Classes
searchable: false
settings:
  byteLimit: null
  charLimit: 150
  code: true
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
