columnSuffix: null
contentColumnType: string
handle: companyName
instructions: 'Shown in the footer as the copyright holder.'
name: 'Company Name'
searchable: false
settings:
  byteLimit: null
  charLimit: 50
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
