columnSuffix: null
contentColumnType: text
fieldGroup: ab74bc93-83f6-4d36-a227-7a3150daec15 # Singles Fields
handle: contactFormThanks
instructions: 'Displayed after submitting the contact form. Can be left blank and a default message will display.'
name: 'Contact Form Thank You'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '3'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
