columnSuffix: null
handle: headingFullWidth
instructions: 'By default, the max width of the headings will be the same as the text blocks. Turn on to make them go full width.'
name: 'Heading Full Width'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: 'Full Width'
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
