columnSuffix: null
handle: headingLevel
instructions: null
name: 'Heading Level'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - H1
        -
          - value
          - '1'
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'H2 (Default)'
        -
          - value
          - '2'
        -
          - icon
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - H3
        -
          - value
          - '3'
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H4
        -
          - value
          - '4'
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H5
        -
          - value
          - '5'
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H6
        -
          - value
          - '6'
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
