columnSuffix: hqdymqov
handle: heading
instructions: null
name: Heading
searchable: false
settings:
  advancedLinkFields: null
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: 95ce255a-2242-4832-a7bd-6ef99ba868c1 # General
  fullGraphqlData: true
  headingLevels:
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options:
    __assoc__:
      -
        - fontSize
        -
          __assoc__:
            -
              - options
              -
                - tiny
                - small
                - big
                - huge
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - undo
    - redo
    - findAndReplace
    - '|'
    - bold
    - italic
    - link
    - superscript
    - subscript
    - fontColor
    - fontSize
    - '|'
    - removeFormat
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
