columnSuffix: null
handle: headingFullWidth
instructions: 'By default, the max width is limited for readability. Turn on to go full width.'
name: 'Full Width'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: 'Full Width'
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
