columnSuffix: mybfonzf
handle: heroSubheading
instructions: null
name: 'Herobar - Subheading'
searchable: false
settings:
  advancedLinkFields:
    - target
    - download
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: true
  headingLevels:
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - undo
    - redo
    - findAndReplace
    - '|'
    - bold
    - italic
    - link
    - subscript
    - superscript
    - '|'
    - removeFormat
    - sourceEditing
  wordLimit: 50
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
