columnSuffix: null
contentColumnType: string
handle: herobar
instructions: null
name: Herobar
searchable: false
settings:
  entryTypes:
    - 75f7d82b-4d45-477b-848c-4f539cfe3469
  maxEntries: 1
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
