columnSuffix: null
contentColumnType: string
handle: imagePair
instructions: null
name: 'Image Pair'
searchable: false
settings:
  entryTypes:
    - 4c25b3bd-91d8-40bf-88d2-394da12d5156
  maxEntries: 2
  minEntries: 2
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
