columnSuffix: null
handle: imageBlock
instructions: null
name: 'Image Block'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - fc3034e2-dcef-4781-b247-7e52cc007b39 # Heading
    -
      __assoc__:
        -
          - uid
          - 88653b5e-8ca3-4e44-85c0-6f158c9eca99 # Text Block
    -
      __assoc__:
        -
          - uid
          - 1dc47a8f-f250-4ac6-a46d-a8c63a0c6fd5 # Image
  includeTableView: false
  maxEntries: 3
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
