columnSuffix: null
contentColumnType: string
handle: imageGridImages
instructions: null
name: 'Image Grid'
searchable: false
settings:
  entryTypes:
    - 58346c7e-0919-434f-b536-e9dae15e85c8
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
