columnSuffix: null
contentColumnType: string
fieldGroup: c763c881-9bb8-49e1-8297-dc71ed74d29a # Common
handle: imageGridImages
instructions: null
name: 'Image Grid'
searchable: false
settings:
  contentTable: '{{%matrixcontent_imagegridimages}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
