columnSuffix: cywieaob
contentColumnType: string
handle: imageVerticalAlign
instructions: null
name: 'Image Vertical Alignment'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - end
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
