columnSuffix: null
contentColumnType: string
fieldGroup: c763c881-9bb8-49e1-8297-dc71ed74d29a # Common
handle: pdf
instructions: null
name: PDF
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - pdf
  defaultUploadLocationSource: 'volume:e797d026-fc3a-408a-a1c8-c17aa4f57f3d' # Assets
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:e797d026-fc3a-408a-a1c8-c17aa4f57f3d' # Assets
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
