columnSuffix: null
handle: phoneNumber
instructions: 'The number should include the country code, such as +1-403-555-5555. Enter a label to change how it appears on the site.'
name: 'Phone Number'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  types:
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
