columnSuffix: bcsosdei
handle: sectionPadding
instructions: null
name: 'Section Padding'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Normal (py-12)'
        -
          - value
          - py-12
        -
          - default
          - 1
    -
      __assoc__:
        -
          - label
          - 'Large (py-16)'
        -
          - value
          - py-16
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Extra Large (py-24)'
        -
          - value
          - py-24
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
