columnSuffix: null
contentColumnType: string
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  entryTypes:
    - 1ca3f937-5a8b-4504-a7c3-22feb254fd6c
  maxEntries: 1
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
