contentColumnType: string
fieldGroup: 2cabf0a4-e1b0-4c44-a840-7c9bd36e75b7 # SEO
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  contentTable: '{{%matrixcontent_seo}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
