columnSuffix: mazbglil
contentColumnType: text
fieldGroup: c763c881-9bb8-49e1-8297-dc71ed74d29a # Common
handle: textBlock
instructions: null
name: 'Text Block'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 3ccf3102-3b57-4a41-8571-700d76e6afca # Standard
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
