columnSuffix: kisotpib
handle: textBlockSimple
instructions: null
name: 'Text Block Simple'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  css: null
  defaultTransform: null
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  options:
    __assoc__:
      -
        - fontSize
        -
          __assoc__:
            -
              - options
              -
                - tiny
                - small
                - big
                - huge
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - undo
    - redo
    - '|'
    - bold
    - italic
    - link
    - superscript
    - subscript
    - fontColor
    - fontSize
    - '|'
    - bookmark
    - removeFormat
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
