columnSuffix: kisotpib
contentColumnType: text
fieldGroup: c763c881-9bb8-49e1-8297-dc71ed74d29a # Common
handle: textBlockSimple
instructions: null
name: 'Text Block Simple'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 9cf43e1b-e9c6-4233-9ac8-ef908559899b # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
