columnSuffix: null
handle: videoEmbedType
instructions: null
name: 'Video Embed Type'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - oEmbed
        -
          - value
          - oembed
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - iFrame
        -
          - value
          - iframe
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
