columnSuffix: kuaiidjs
handle: videoOembed
instructions: 'Paste the embed URL.'
name: Video
searchable: false
settings:
  url: ''
translationKeyFormat: null
translationMethod: none
type: wrav\oembed\fields\OembedField
