dateModified: 1733357285
email:
  fromEmail: $FROM_EMAIL
  fromName: $FROM_EMAIL_NAME
  replyToEmail: null
  template: null
  transportSettings:
    encryptionMethod: tls
    host: $SMTP_HOST_NAME
    password: $POSTMARK_API_KEY
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $POSTMARK_API_KEY
  transportType: craft\mail\transportadapters\Smtp
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: '@webroot/assets/pdfs'
    type: craft\fs\Local
    url: '@web/assets/pdfs'
  blog:
    hasUrls: true
    name: Blog
    settings:
      path: '@webroot/assets/blog'
    type: craft\fs\Local
    url: '@web/assets/blog'
  general:
    hasUrls: true
    name: General
    settings:
      path: '@webroot/assets/general'
    type: craft\fs\Local
    url: '@web/assets/general'
  ogImages:
    hasUrls: true
    name: 'Sharing Images'
    settings:
      path: '@webroot/assets/og'
    type: craft\fs\Local
    url: '@web/assets/og'
meta:
  __names__:
    0a84d050-b078-4401-9449-cdda849f722b: Contact # Contact
    1ca3f937-5a8b-4504-a7c3-22feb254fd6c: SEO # SEO
    1dc47a8f-f250-4ac6-a46d-a8c63a0c6fd5: Image # Image
    2b537640-9acd-4e53-a1b4-f497d2e79cd0: Blog # Blog
    2ebda50a-529a-4080-a436-20f253d62a8b: Blocks # Blocks
    3c4b2037-49c2-46d7-8e32-de494f9fb4ff: 'Neo Column Image - Small' # Neo Column Image - Small
    3ccf3102-3b57-4a41-8571-700d76e6afca: Standard # Standard
    4d1d39e1-6786-40b9-8622-025a3554e456: 'Site Information' # Site Information
    4deb1488-ff4e-4359-91ed-22574db39b8e: 'Accordion Wrapper' # Accordion Wrapper
    4e2f2db3-5884-4b3c-807d-936f4f7dbcf6: Card # Card
    5f2efa0b-1e87-4d02-a636-f17256ef85d1: 'Block Width' # Block Width
    6eedec95-8e5a-49e4-8206-33ff056d1664: 'Image Size' # Image Size
    7a5706d7-fc4f-4422-a8d3-9f6e5448d974: Text # Text
    7ee19ba5-8919-4ba7-8a82-e84de143fc1f: Cards # Cards
    8b7f28d8-533c-4c53-befc-8bf5de329775: URLs # URLs
    08c0e2a2-aaf5-48e9-bed6-e1f8fc7ce863: 'Herobar - Subheading' # Herobar - Subheading
    8f2af3e8-cdf5-4c6b-921e-814f25286901: 'Contact Form' # Contact Form
    09cd580c-e508-46a1-85a9-66581dd3a958: 'Element Id' # Element Id
    9cf43e1b-e9c6-4233-9ac8-ef908559899b: Simple # Simple
    12bf30a3-ae66-402c-aa6a-1957b9eace70: Card # Card
    14b6e20f-f619-4fbc-9b76-72460ba1423b: 'Neo Column Image - Extra Small' # Neo Column Image - Extra Small
    17ed004b-264f-4318-be4a-407867219887: 'Image Align' # Image Align
    22bd92e8-fa46-4ac8-b91d-7b8a84bebccb: 'Accordion Icon' # Accordion Icon
    41e7d3e7-7f22-4eec-8732-1a4b2cc13182: 'Accordion Content' # Accordion Content
    48ab6525-2753-4564-a94c-19b9a23de6df: 'Blog Categories' # Blog Categories
    48b81495-c226-4048-afdd-066e97f6a4a5: 'Contact Form Thank You' # Contact Form Thank You
    49a23caf-c4e8-450b-a4d5-7acbe7d2ef69: 'Button Text' # Button Text
    49c7c1d7-292b-450a-bf9e-c53ee0c295f8: 'Accordion Icon' # Accordion Icon
    50ce781f-8f6e-4eeb-b0b7-faa9e9821913: 'Text Block' # Text Block
    52c2bd62-048d-4695-be78-f0110b0727de: Button # Button
    55c62e14-e98e-4d1a-a181-845f6ebf20e4: Heading # Heading
    55db9051-b419-4237-b226-acfb99d40498: 'Image Link' # Image Link
    63c94dc6-f41f-43d2-ae4c-b1112b55a62a: 'Social Media' # Social Media
    64a1d559-0f30-491d-92c9-177cf340853c: 'Company Name' # Company Name
    64ec34a3-ecdf-4518-b59f-faaa5d33b8a9: 'Post Content - Image' # Post Content - Image
    68c02e53-bd4b-45e6-8721-dfa278498dbb: 'Herobar Image' # Herobar Image
    72bf15bd-1c10-49b7-9d48-b1192343eea6: 'Accordion Heading' # Accordion Heading
    75f7d82b-4d45-477b-848c-4f539cfe3469: Hero # Hero
    77e77066-5f46-47e0-8cd1-44df0c9e2033: 'Social Media' # Social Media
    80ffc64e-4e53-4ba1-8e8f-95d4f45b8946: 'Text Align' # Text Align
    84d2deef-d6fe-4a07-b967-b71469d68219: 'SEO - Sharing Image Alt' # SEO - Sharing Image Alt
    95ce255a-2242-4832-a7bd-6ef99ba868c1: General # General
    95e5ecb2-f98f-455b-bd08-580743d5fa53: 'Text Align Center (Mobile)' # Text Align Center (Mobile)
    414f0663-ff97-44ab-b402-98890d76f713: 'SEO - Page Title' # SEO - Page Title
    486e0db8-6cbd-4cd7-85af-77040ab2b43c: Image # Image
    511f52f1-d8bb-4d5e-820d-d3f65afcfdc9: 'Text Block Simple' # Text Block Simple
    554d5c17-904d-4637-9bfc-f85a9f70ba44: Blocks # Blocks
    609f74fc-ee58-439b-afdb-10d9c919d562: Cards # Cards
    681bd2d8-cf04-4239-bcc5-a1bbcc3c8625: 'Card Text Block' # Card Text Block
    683dcf54-f292-4177-bc23-e0af464cc90e: 'Public Schema' # Public Schema
    733fd8a3-3ba2-49a2-bb77-c60b52b6bc66: 'Post Content' # Post Content
    787e1739-73f9-4cc5-876c-48a53d41a987: 'Post Categories' # Post Categories
    809bc4b9-bc38-4d55-bb2c-4f2983ea3cfc: 'Image Caption' # Image Caption
    2062b2bd-5662-4e7c-a7cf-0f05a4b4da60: 'Herobar - Heading' # Herobar - Heading
    2338f10f-0595-4642-bd0c-077886b0da3b: Accordion # Accordion
    3782b2bb-7c19-4392-a96c-6ee2ed24a4cd: 'SEO - Sharing Image' # SEO - Sharing Image
    4294d06d-5c1a-4afe-83cb-048be5c27d4a: 'Neo Column Image - Large' # Neo Column Image - Large
    5806aa3f-0845-4297-a1c8-edc07c16ef07: 'Section Start' # Section Start
    8794b2b7-43f4-4b76-87bb-e1875f1d0357: 'Contact Thanks' # Contact Thanks
    23405c96-1469-4872-a55a-6488791f767a: Default # Default
    25053ba9-0cb9-477b-98bb-ef1d6c5bd9ea: 'Contact Thanks' # Contact Thanks
    42773db2-f2e9-40a9-ab5e-e3406f1a6a25: 'XM Craft Starter' # XM Craft Starter
    49523c85-f034-4218-a653-a10e294faac5: Homepage # Homepage
    053794be-63d9-4bcb-bdce-8452a3bf84b3: 'Social Media - URLs - Facebook' # Social Media - URLs - Facebook
    88653b5e-8ca3-4e44-85c0-6f158c9eca99: 'Text Block' # Text Block
    144007f7-7bab-40c2-9327-b324abf12787: 'Neo Column Image - Medium' # Neo Column Image - Medium
    941223b2-225a-4a1c-8095-3ef96f00d2f5: Services # Services
    a9d87289-cfe2-4244-bc61-fcf804f19e75: 'SEO - Meta Description' # SEO - Meta Description
    b2bcdb56-a6f3-4968-8e8b-ec20a7512d37: Herobar # Herobar
    b6b7c09d-6eb1-403b-bfbe-2be795f73901: 'Image Grid' # Image Grid
    b7e52fb1-8f8c-42af-b4dd-89f7bff35de2: 'Accordion Wrapper' # Accordion Wrapper
    b700f3be-bc0a-4a9c-bbd6-cc795a93bc10: 'Sharing Images' # Sharing Images
    c0a4b738-d7e7-4400-9576-7e279127345f: 'Card Heading' # Card Heading
    c2e7e94e-1754-4c1c-b74d-ba5cf4d0f6b3: 'Featured Image' # Featured Image
    c3bdff5b-2014-42e0-87b1-372f17b8ec0e: 'Image Vertical Alignment' # Image Vertical Alignment
    c88e53c0-b0e2-4f2e-8b79-69954becb0f7: Video # Video
    c2939a10-1c98-4789-8a72-cc8985158379: Blog # Blog
    d7f5b5cc-8e4d-422b-ba64-da1a79121801: Classes # Classes
    d9b45246-8d18-46e0-9a98-ac7b65120828: About # About
    d438c1a3-baf2-4366-9942-1dfcd9b7454a: 'Accordion Icon' # Accordion Icon
    d9009def-1bb9-482d-8539-be1829106860: 'Post Content - Text' # Post Content - Text
    dadbdcf6-f9f1-4d87-9c01-c567a77669ff: Video # Video
    e16fd2de-54c9-4363-a6bd-d3a6756c0720: Uppercase # Uppercase
    e797d026-fc3a-408a-a1c8-c17aa4f57f3d: Assets # Assets
    e9250cf7-3f95-4113-85e5-0140eb887bfe: SEO # SEO
    ec34d844-46a7-4389-965e-a1a4048a0798: Accordion # Accordion
    f4c0b7f9-3337-442b-b4fa-8f3cf2bbee89: Services # Services
    f9c080c6-18df-4ea2-a482-b955a918cdc7: Card # Card
    fa2ad779-73fc-442c-9c92-1ae549690452: Summary # Summary
    fc51aef1-4c76-49e7-bbd0-80b2827d65fe: Blog # Blog
    fc3034e2-dcef-4781-b247-7e52cc007b39: Heading # Heading
    fde5281f-1a78-4749-abcc-3c136ffc0258: 'Button Link' # Button Link
    fe9ab73f-86a5-45dd-8efd-91ea40ad88ac: 'Card Image' # Card Image
    ffc736cb-53c0-4f0c-9682-b810b51e72b2: Contact # Contact
plugins:
  assetrev:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: ''
      prependSubject: 'Message from XM Craft Starter website'
      successFlashMessage: 'Your message has been sent.'
      toEmail: $FROM_EMAIL
  contact-form-extensions:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      confirmationSubject: ''
      confirmationTemplate: ''
      enableConfirmationEmail: ''
      enableDatabase: '1'
      enableTemplateOverwrite: ''
      notificationTemplate: ''
      recaptcha: ''
      recaptchaDataBadge: bottomright
      recaptchaDebug: ''
      recaptchaHideBadge: ''
      recaptchaSecretKey: ''
      recaptchaSiteKey: ''
      recaptchaThreshold: '0.5'
      recaptchaTimeout: '5'
      recaptchaVersion: ''
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      honeypotParam: repeatEmail
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: Z06UU8T1NEF1DX23V6CTKVYM
    schemaVersion: 5.1.0.1
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'XM Craft Starter'
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: America/Edmonton
