defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 554d5c17-904d-4637-9bfc-f85a9f70ba44 # Blocks
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  42773db2-f2e9-40a9-ab5e-e3406f1a6a25: # XM Craft Starter
    enabledByDefault: true
    hasUrls: true
    template: _default.twig
    uriFormat: contact
type: single
