defaultPlacement: end
enableVersioning: true
handle: testPage
name: 'Test Page'
propagationMethod: all
siteSettings:
  42773db2-f2e9-40a9-ab5e-e3406f1a6a25: # XM Craft Starter
    enabledByDefault: true
    hasUrls: true
    template: _default.twig
    uriFormat: test-page
type: single
